version: '{build}'
image: Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

nuget:
  disable_publish_on_pr: true

build_script:
- ps: dotnet run -p src/build/build.csproj

test: off

artifacts:
- path: src\SharpCompress\bin\Release\*.nupkg