version: '{build}'
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

nuget:
  disable_publish_on_pr: true

before_build:
  - cmd: dotnet restore

build:
  parallel: true
  verbosity: minimal

after_build:
- dotnet pack "src\SharpCompress\SharpCompress.csproj" -c Release

test_script:
- dotnet test --no-build .\tests\SharpCompress.Test\SharpCompress.Test.csproj

artifacts:
- path: src\SharpCompress\bin\Release\*.nupkg