name: SharpCompress
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - run: dotnet run -p src/build/build.csproj
    - uses: actions/upload-artifact@v2
      with:
        path: artifacts/*
